version: '3.8'

services:
  # -----------------
  # Database Service
  # -----------------
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=experiments
    volumes:
      # This persists the database data on your local machine
      - postgres_data:/var/lib/postgresql/data
    ports:
      # You can connect to the DB from your host machine on port 5432
      - "5432:5432"
    networks:
      - experiment-net

  # ---------------------
  # Experiment 1 Service (e.g., lower learning rate)
  # ---------------------
  lunar-lander-exp1:
    build: .
    container_name: lunar-lander-exp1
    environment:
      # --- Experiment & DB Config ---
      - DB_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=experiments
      - EXPERIMENT_ID=exp-lr-low-gamma-high
      # --- Hyperparameters ---
      - LEARNING_RATE=0.0001
      - GAMMA=0.995
      - BATCH_SIZE=256
      - FIRST_HID=350
      - SECOND_HID=150
      - EPSILON_DECAY=0.99
    depends_on:
      - db
    networks:
      - experiment-net
    volumes:
      - ./outputs/exp1:/app/outputs

  # ---------------------
  # Experiment 2 Service (e.g., higher learning rate)
  # ---------------------
  lunar-lander-exp2:
    build: .
    container_name: lunar-lander-exp2
    environment:
      # --- Experiment & DB Config ---
      - DB_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=experiments
      - EXPERIMENT_ID=exp-lr-high-gamma-low
      # --- Hyperparameters ---
      - LEARNING_RATE=0.001
      - GAMMA=0.99
      - BATCH_SIZE=512
      - FIRST_HID=350
      - SECOND_HID=150
      - EPSILON_DECAY=0.99
    depends_on:
      - db
    networks:
      - experiment-net
    volumes:
      - ./outputs/exp2:/app/outputs

# Define the network that allows containers to communicate
networks:
  experiment-net:
    driver: bridge

# Define the volume for persistent database storage
volumes:
  postgres_data:

